#TODO: MAKE canAISelect var true after player selects his card
#TODO: MAKE A COMPLETE BATTLE SYSTEM FOR DETERMINE WIN
#       -> SELECT 1 CARD FROM YOUR SIDE AND FROM CHOOSE ATTACK AND ENEMY CARD TO PERFORM AN ATTACK